#!/bin/bash

# Declaration
die () {
    echo Failed to $1
    exit 1
}

FILE_LOCATION=( "vim/vimrc" "bash_additions" "scripts" "i3/config" "i3/statusbar" "vim/UltiSnips")
LINK_LOCATION=( ".vimrc" ".bash_additions" ".scripts" ".i3/config" ".i3status.conf" ".vim/UltiSnips")
AMOUNT_FILES=${#LINK_LOCATION[@]}
(( AMOUNT_FILES-- ))
PREFIX=~/.dotfiles/

# Action
cd ~ || die "cd to ~"
mv dotfiles .dotfiles || die "move dotfiles to .dotfiles"

for i in `seq 0 $AMOUNT_FILES`; do
    file="$PREFIX${FILE_LOCATION[$i]}"
    link="${LINK_LOCATION[$i]}"
    ln -n -s -f "$file" "$link" || die "to create link from $link to $file"
    # -f = replace existing, -n = treat as normal if its a directory
done

echo '' >> .bashrc || die "change .bashrc"
echo 'source ~/.dotfiles/bash_additions/all' >> .bashrc || die "change .bashrc"
