#!/bin/bash

filename="count"

if [ ! -f $filename ]; then
    echo "0" >$filename
fi

num=`cat $filename`
if [ -v $BLOCK_BUTTON ]; then
    echo $num
    echo $num
    exit
fi
# else

(( num++ ))
echo $num >$filename

echo $num
echo $num

(
    sleep 1
    num=`cat $filename`
    (( num-- ))
    if [ $num == "0" ]; then
        rm $filename
    else
        echo $num >$filename
    fi
    pkill -RTMIN+1 i3blocks
) &>/dev/null </dev/null & disown
