#!/bin/bash
# Get interface
IF=$(ip route | awk '/^default/ { print $5 ; exit }')
# Exit if no wifi
[[ ! -d /sys/class/net/${IF} ]] && exit
# Check if down, if it is, then display "down"
if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo down # full text
  echo down # short text
  echo \#FF0000 # color
  exit
fi
# Do some more stuff
case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac
# if no interface is found, use the first device with a global scope
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")
# Right click copies address
case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac
# Display address
echo "$IPADDR" # full text
echo "$IPADDR" # short text
